### ISSUE TITLE
[TODO] 20220421

### ISSUE THREAD

**Issue by jingfelix** [jingfelix/jingfelix.github.io#3]
- [x] 使用 [MDUI](https://www.mdui.org/) 重写式样
- [x] 重写 build.py，延伸出一个用于构建 html 对象的 Python package
- [x] 取消了 html 支持，提供完整 markdown 支持

**Comment by jingfelix** [comment]
Everything's done. Issue closed.
